plugins { id 'com.android.application' }

android {
    namespace 'com.openai.workouttracker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ahmed.workouttracker.gif'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '3.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
